### PR TITLE
prabir

### PR DESCRIPTION
**Pull request by PrabirKumarMahatha**
added something

### CODE REVIEW

**Review by deysubho — COMMENTED** [review]
there is a conflict in your pilled request kindly resolve it.

**Review by deysubho — COMMENTED** [review]
there is a conflict in your pilled request kindly resolve it.

**Comment by PrabirKumarMahatha** [comment]
i am just compress  your code from a paragraph to 2 lines

**Comment by PrabirKumarMahatha** [comment]
either you merge it or i kill you

**Comment by PrabirKumarMahatha** [comment]
I resolved the conflict

**Comment by deysubho** [comment]
Thank You.

**Pull request merged**
